---
abstract: 'DAS-style access to a chado database'
author: []
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-DB-Das-Chado
provides:
  Bio::DB::Das::Chado:
    file: lib/Bio/DB/Das/Chado.pm
    version: 2
  Bio::DB::Das::Chado::Segment:
    file: lib/Bio/DB/Das/Chado/Segment.pm
  Bio::DB::Das::Chado::Segment::Feature:
    file: lib/Bio/DB/Das/Chado/Segment/Feature.pm
  Bio::DB::Das::ChadoIterator:
    file: lib/Bio/DB/Das/Chado.pm
requires:
  Bio::Root::Version: 1.006
  DBD::Pg: 0
  DBI: 0
  URI::Escape: 0
resources:
  license: http://dev.perl.org/licenses/
version: 2
