---
name: Bio-SamTools
version: 0.01
author:
  - 'Lincoln Stein <lincoln.stein@gmail.com>'
abstract: The GMOD Generic Genome Browser
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.008
build_requires:
  ExtUtils::CBuilder: 0
provides:
  Bio::DB::Bam::AlignWrapper:
    file: lib/Bio/DB/Sam.pm
  Bio::DB::Bam::Alignment:
    file: lib/Bio/DB/Sam.pm
  Bio::DB::Sam:
    file: lib/Bio/DB/Sam.pm
    version: 0.01
  Bio::DB::Sam::FetchIterator:
    file: lib/Bio/DB/Sam.pm
  Bio::DB::Sam::ReadIterator:
    file: lib/Bio/DB/Sam.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
