---
name: Bio-SamTools
version: 0.02
author:
  - 'Lincoln Stein <lincoln.stein@gmail.com>'
abstract: The GMOD Generic Genome Browser
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.008
build_requires:
  ExtUtils::CBuilder: 0
provides:
  Bio::DB::Bam::AlignWrapper:
    file: lib/Bio/DB/Bam/AlignWrapper.pm
  Bio::DB::Bam::Alignment:
    file: lib/Bio/DB/Bam/Alignment.pm
  Bio::DB::Bam::FetchIterator:
    file: lib/Bio/DB/Bam/FetchIterator.pm
  Bio::DB::Bam::Query:
    file: lib/Bio/DB/Bam/Query.pm
  Bio::DB::Bam::ReadIterator:
    file: lib/Bio/DB/Bam/ReadIterator.pm
  Bio::DB::Bam::Target:
    file: lib/Bio/DB/Bam/Target.pm
  Bio::DB::Sam:
    file: lib/Bio/DB/Sam.pm
    version: 0.02
  Bio::DB::Sam::Segment:
    file: lib/Bio/DB/Sam/Segment.pm
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
